<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl();

$nombredias = array(
	"1" => "Lunes","2" => "Martes",
	"3" => "Miercoles","4" => "Jueves",
	"5" => "Viernes","6" => "Sabado",
	"7" => "Domingo"
);

$nombremes = array(
	"1" => "Enero","2" => "Febrero",
	"3" => "Marzo","4" => "Abril",
	"5" => "Mayo","6" => "Junio",
	"7" => "Julio","8" => "Agosto",
	"9" => "Setiembre","10" => "Octubre",
	"11" => "Noviembre","12" => "Diciembre",
);

$dias = array();
$diaslima = array();
$diasprovincia = array();
for ($i=1; $i<14; $i++)
{
	$diasemana = date("N", strtotime($i." days"));
	$mes = date("m", strtotime($i." days"));
	$mesint = intval($mes);
	$dias[] = array(
		"dia" => date("d", strtotime($i." days")),
		"mes" => $mes,
		"anio" => date("Y", strtotime($i." days")),
		"dia_semana" => $diasemana,
		"nombredia" => (isset($nombredias[$diasemana]))?$nombredias[$diasemana]:"",
		"nombremes" => (isset($nombremes[$mesint]))?$nombremes[$mesint]:""
	); 

	if($i>=2){
		$diaslima[] = array(
			"dia" => date("d", strtotime($i." days")),
			"mes" => $mes,
			"anio" => date("Y", strtotime($i." days")),
			"dia_semana" => $diasemana,
			"nombredia" => (isset($nombredias[$diasemana]))?$nombredias[$diasemana]:"",
			"nombremes" => (isset($nombremes[$mesint]))?$nombremes[$mesint]:""
		);
	}

	if($i>=4){
		$diasprovincia[] = array(
			"dia" => date("d", strtotime($i." days")),
			"mes" => $mes,
			"anio" => date("Y", strtotime($i." days")),
			"dia_semana" => $diasemana,
			"nombredia" => (isset($nombredias[$diasemana]))?$nombredias[$diasemana]:"",
			"nombremes" => (isset($nombremes[$mesint]))?$nombremes[$mesint]:""
		);
	}

}

if($this->getActiveMapa()){ ?>
<script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->getApiKey();?>" async defer></script> 
<?php } ?>
<script type="text/javascript">
	window.statusmapa = <?= ($this->getActiveMapa())?'true':'false' ?>;
	window.baseurlvex = '<?= $url ?>';
	window.diasvex = JSON.parse('<?= json_encode($dias) ?>');
	window.limaid = 524;

	window.diasvexlima = JSON.parse('<?= json_encode($diaslima) ?>');
	window.diasvexprovincia = JSON.parse('<?= json_encode($diasprovincia) ?>');
</script>