<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \MageWorx\Locations\Block\Adminhtml\Location\Edit\Attributes $block */
?>
<div>
    <a href="<?= $block->escapeUrl("https://support.mageworx.com/manuals/store-locator/#store-attributes")?>" target="_blank">
        <?= $block->escapeHtml(__("Learn more about store attributes"))?>
    </a>
</div>
