<?php
/** @var $block \MageWorx\StoreLocator\Block\MainPage */
?>
    <div class="mw-store-locator-inpage-content">
        <div id="mw-store-locator-locations" class="mw-store-locator-locations">
        </div>
    </div>
<script>
    require(["jquery"], function ($) {
        $(document).ready(function () {
            var url = '<?= /* @noEscape */ $block->getBaseUrl() ?>store_locator/location/updatemainpage';

            $.ajax({
                url: url + '?_=' + new Date().getTime(),
                type: 'POST',
                isAjax: true,
                dataType: 'html',
                showLoader: true,
                success: function (xhr, status, errorThrown) {
                    $('#mw-store-locator-locations').html(xhr);
                    $('#mw-store-locator-locations').trigger('map_initialize');
                },
                error: function (xhr, status, errorThrown) {
                    console.log('There was an error loading stores popup.');
                    console.log(errorThrown);
                }
            });
        });
    })
</script>
