<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

?>
<?php
/**
 * Location Page view template
 *
 * @var $block MageWorx\LocationPages\Block\Location
 */
/** @var \MageWorx\Locations\Api\Data\LocationInterface $location */
$location = $block->getCurrentLocation();
if ($location) :?>
    <div id="mw-store-locator-details-page">
        <?= $block->getMapHtml($location) ?>
        <div class="mw-sl__details"><h2 class="mw-sl__details__name"><?= $block->escapeHtml($location->getName()) ?></h2>
            <ul class="mw-sl__details__list">
                <li class="mw-sl__details__item mw-sl__details__item--location">
                    <?= $block->escapeHtml($location->getName()); ?>, <?=
                    $block->escapeHtml($location->getCity()); ?>
                    <br/>
                    <?= $location->getRegion() == \MageWorx\Locations\Model\Source\Region::NO_REGIONS ? '' :
                            $block->escapeHtml($block->getLocationsRegion($location)) . ', '; ?>
                    <?= $block->escapeHtml($location->getPostcode()); ?>, <?=
                        $block->escapeHtml($location->getCountry()); ?>
                    <br/>
                </li>
                <li class="mw-sl__details__item mw-sl__details__item--direction">
                    <a href="<?= $block->escapeUrl($block->getRouteUrl($location)); ?>" target="_blank"><?=
                        $block->escapeHtml(__('Get direction')) ?></a>
                </li>
                <?php if ($location->getPhoneNumber()) : ?>
                    <li class="mw-sl__details__item mw-sl__details__item--tel">
                        <a href="tel:<?= $block->escapeUrl($location->getPhoneNumber()); ?>">
                            <?= $block->escapeHtml($location->getPhoneNumber()); ?>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($block->isWorkingHoursEnabled($location)): ?>
                <li class="mw-sl__details__item mw-sl__details__item--hours">
                    <span class="store__info_<?= (int)$location->getId() ?>"></span> <span
                            class="store__info_wh_<?= (int)$location->getId() ?>"></span>
                </li>
                <?php endif; ?>
            </ul>
        </div>
        <div class="mw-sl__store-info">
            <div class="mw-sl__store-info__wrapper">
                <div class="mw-sl__store-info__description">
                    <?php if ($location->getDescription()) : ?>
                        <h2 class="mw-sl__store-info__heading"><?= $block->escapeHtml(__('Store description')) ?></h2>
                        <p class="mw-sl__store-info__content"><?= $block->getDescriptionHtml($location) ?></p>
                    <?php endif; ?>
                    <ul class="mw-sl__store-info__additional">
                        <?php if ($location->getEmail()) : ?>
                            <li class="mw-sl__store-info__additional__item mw-sl__store-info__additional__item--email">
                                <a
                                        href="mailto:<?= $block->escapeUrl($location->getEmail()); ?>">
                                    <?= $block->escapeHtml($location->getEmail()); ?>
                                </a></li>
                        <?php endif; ?>
                        <?php if ($location->getWebsiteUrl()) : ?>
                            <li class="mw-sl__store-info__additional__item mw-sl__store-info__additional__item--website">
                                <a
                                        href="https://<?= $block->escapeUrl($location->getWebsiteUrl()); ?>"
                                        target="_blank">
                                    <?= $block->escapeUrl($location->getWebsiteUrl()); ?></a></li>
                        <?php endif; ?>
                    </ul>
                    <ul class="mw-sl__store-info__socialslist">
                        <?php if ($location->getInstagram()) : ?>
                            <li class="mw-sl__store-info__socialslist__item"><a
                                        href="https://instagram.com/<?= $block->escapeUrl(
                                            $location->getInstagram()
                                                                    ); ?>" target="_blank"><i
                                            class="mw-sl__icon mw-sl__icon--instagram"><img
                                                src="<?= $block->escapeUrl($block->getViewFileUrl(
                                                    'MageWorx_StoreLocator::images/svg/instagram.svg'
                                                )); ?>"
                                                alt="<?= $block->escapeHtml(__('Instagram icon')) ?>"/></i></a>
                            </li>
                        <?php endif; ?>
                        <?php if ($location->getFacebook()) : ?>
                            <li class="mw-sl__store-info__socialslist__item"><a
                                        href="https://facebook.com/<?= $block->escapeUrl(
                                            $location->getFacebook()
                                                                   ); ?>" target="_blank"><i
                                            class="mw-sl__icon mw-sl__icon--facebook"><img
                                                src="<?= $block->escapeUrl($block->getViewFileUrl(
                                                    'MageWorx_StoreLocator::images/svg/facebook.svg'
                                                )); ?>"
                                                alt="<?= $block->escapeHtml(__('Facebook icon')) ?>"/></i></a></li>
                        <?php endif; ?>
                        <?php if ($location->getWhatsapp()) : ?>
                            <li class="mw-sl__store-info__socialslist__item">
                                <a href="https://wa.me/<?= $block->escapeUrl($location->getWhatsapp()); ?>"
                                   target="_blank"><i
                                            class="mw-sl__icon mw-sl__icon--whatsapp"><img
                                                src="<?= $block->escapeUrl($block->getViewFileUrl(
                                                    'MageWorx_StoreLocator::images/svg/whatsapp.svg'
                                                )); ?>"
                                                alt="<?= $block->escapeHtml(__('Whatsapp icon')) ?>"/></i></a></li>
                        <?php endif; ?>
                        <?php if ($location->getSkype()) : ?>
                            <li class="mw-sl__store-info__socialslist__item">
                                <a href="skype:<?= $block->escapeUrl($location->getSkype()); ?>?call"><i
                                            class="mw-sl__icon mw-sl__icon--skype">
                                        <img src="<?= $block->escapeUrl($block->getViewFileUrl(
                                            'MageWorx_StoreLocator::images/svg/skype.svg'
                                        )); ?>" alt="<?= $block->escapeHtml(__('Skype icon')) ?>"/></i>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <div class="mw-extra_attr" id="mw-store-locator-locations">
                        <div class="mw-extra_attr_columns">
                            <ul class="mw-sl__stores__details__icons">
                                <?php foreach ($block->getExtraAttributes() as $attribute) : ?>
                                    <?php if ($location->getData($attribute['attribute_code'])) : ?>
                                        <li class="mw-sl__stores__details__website"><i class="mw-sl__icon mw-sl__icon--website">
                                                <img src="<?= $block->escapeUrl(
                                                    $block->getAttributeIcon($attribute['attribute_code'])
                                                ); ?>"
                                                     alt="<?= $block->escapeHtml(__($attribute['frontend_label'])) ?>"/>
                                            </i>
                                            <span>
                                <?= $block->escapeHtml(__($attribute['frontend_label'])) ?>
                            <span>
                                        </li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <?php if ($location->getImagePath()) : ?>
                    <div class="mw-sl__store-info__image"><img
                                src="<?= $block->escapeUrl($block->getLocationImageUrl($location->getImagePath())); ?>"
                                alt="<?= $block->escapeHtml(
                                    $location->getName()
                                     ) ?>"/></div>
                <?php endif; ?>
            </div>
        </div>
        <div class="mw-sl__store-info">
            <?= $block->getWorkingHoursHtml($location) ?>
        </div>
    </div>

    <script type="text/javascript">
        require(["jquery", "uiRegistry"], function ($, registry) {
            var mwLocations = JSON.parse('<?= $block->escapeJs(json_encode(['location_ids' => [(int)$location->getId()]]))?>');
            mwLocations['store_id'] = <?= (int)$block->getCurrentStoreId()?>;
            <?php if($block->isWorkingHoursEnabled($location)): ?>
                if (typeof mwLocations !== 'undefined') {
                    $.ajax({
                        url: '<?= $block->escapeUrl($block->getWorkingHoursUrl())?>' + '?_=' + new Date().getTime(),
                        type: 'POST',
                        isAjax: true,
                        dataType: 'json',
                        data: mwLocations,
                        success: function (xhr, status, errorThrown) {
                            var items = [];
                            $.each(xhr, function (locationCode, val) {
                                if (typeof (val['isOpen']) !== 'undefined' && typeof (val['info']) !== 'undefined') {
                                    if (val['isOpen']) {
                                        $('.store__info_' + locationCode).addClass('mw-sl__store__info__open');
                                        $('.store__info_' + locationCode).text('Open now');
                                        $('.store__info_wh_' + locationCode).addClass('mw-sl__store__info__open');
                                        $('.store__info_wh_' + locationCode).text(val['info']);
                                    } else {
                                        $('.store__info_' + locationCode).addClass('mw-sl__store__info__closed');
                                        $('.store__info_' + locationCode).text('Closed now');
                                        $('.store__info_wh_' + locationCode).addClass('mw-sl__store__info__closed');
                                        $('.store__info_wh_' + locationCode).text(val['info']);
                                    }
                                }
                            });
                        },
                        error: function (xhr, status, errorThrown) {
                            console.log('There was an error loading stores\' working hours.');
                        }
                    });
                }
            <?php endif; ?>
        });
    </script>
<?php endif; ?>
