<?php
/** @var $block \MageWorx\StoreLocator\Block\Filter */
$locations    = $block->getLocations();
$defaultPlace = $block->getCurrentPlace();
?>
<div class="mw-sl__stores">
    <div class="mw-sl__stores__header">
        <div id="location-header" class="location-header is-active">
            <div class="mw-sl__stores__header__item mw-sl__stores__header__item_pin pin-to-center">
                <i class="mw-sl__icon--pin">
                    <img src="<?= $block->escapeUrl($block->getViewFileUrl('MageWorx_StoreLocator::images/svg/pin.svg')); ?>"
                         alt="<?= $block->escapeHtml(__('Pin icon')) ?>"/>
                </i>
            </div>
            <div class="mw-sl__stores__header__item">
                <p id="sl__stores__current_place" class="mw-sl__stores__current"><?= $block->escapeHtml($block->getCurrentPlaceName()); ?></p>
                <p class="mw-sl__stores__current mw-store-locator-inactive-place mw-sl__stores__current_all_stores">
                    <?= $block->escapeHtml(__('All Stores')); ?>
                </p>
                <?php /** @var \MageWorx\LocationPages\Api\Data\LocationListInterface $place */
                foreach ($block->getParentFilterList() as $place) : ?>
                    <p class="mw-sl__stores__current mw-store-locator-inactive-place mw-sl__stores__current_<?= $block->escapeHtml($place->getId()); ?>">
                        <?= $block->escapeHtml($block->getPlaceNameWithRegion($place)); ?>
                    </p>
                <?php endforeach; ?>
            </div>
            <div class="mw-sl__stores__header__item">
                <i class="mw-sl__icon mw-sl__icon--filter">
                    <img src="<?= $block->escapeUrl($block->getViewFileUrl('MageWorx_StoreLocator::images/svg/filter.svg')); ?>"
                         alt="<?= $block->escapeHtml(__('Filter icon')) ?>"/>
                </i>
            </div>
        </div>
        <?php /** @var $location \MageWorx\Locations\Api\Data\LocationInterface $location */
        foreach ($locations as $location) : ?>
            <div class="location-header" id="location-header_<?= $block->escapeHtml($location->getId()) ?>">
                <div class="mw-sl__stores__header__item mw-sl__stores__header__item_pin">
                    <i class="mw-sl__icon--close">
                        <img src="<?= $block->escapeUrl($block->getViewFileUrl('MageWorx_StoreLocator::images/svg/back.svg')); ?>"/>
                        <span><strong><?= $block->escapeHtml(__('Back'))?></strong></span>
                    </i>
                </div>
                <div class="mw-sl__stores__header__item">
                    <span class="mw-sl__store__info__name"><?= /* @noEscape */ $block->getLocationPageLink($location, __('Store Page'))?></span>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="mw-sl__stores__list" id="mw-sl__stores__list_block">
        <ul>
            <?php /** @var $location \MageWorx\Locations\Api\Data\LocationInterface $location */
            if (count($locations)) :
                foreach ($locations as $location) : ?>
                    <?= /* @noEscape */ $block->getLocationInfoHtml($location); ?>
                <?php endforeach; ?>
                <div class="mw-sl__no-stores" style="display: none"><?= $block->escapeHtml(__('No stores found.')); ?></div>
             <?php else : ?>
                <div class="mw-sl__no-stores"><?= $block->escapeHtml(__('No stores found.'));?></div>
            <?php endif?>
        </ul>
    </div>
    <div class="mw-sl__stores__filters">
        <ul class="mw-sl__stores__details__icons">
            <li class="mw-sl__stores__filters__item mw-sl__stores__filters__item-map">
                <select name="mw-sl__stores__filter" id="mw-sl__stores__filters" class="mw-sl__select" style="width: 100%">
                    <option value="all_stores" id="all_stores">
                        <?= $block->escapeHtml(__('All Stores')); ?>
                    </option>
                    <?php foreach ($block->getParentFilterList() as $place) : ?>
                        <option value="<?= $block->escapeHtml($place->getId()); ?>"
                                id="mw-<?= $block->escapeHtml($place->getId()); ?>">
                            <?= $block->escapeHtml($block->getPlaceNameWithRegion($place)); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </li>
            <li class="mw-sl__stores__filters__item mw-sl__stores__filters__item-map mw-extra_attr">
                <div class="mw-extra_attr_columns">
                    <ul class="mw-sl__stores__details__icons" style="min-width: 300px;">
                        <?php foreach ($block->getExtraAttributes() as $attribute) : ?>
                                <li class="mw-sl__stores__details__website"  style="width: 50%;">
                                    <input type="checkbox"
                                           id="<?= $block->escapeHtml($attribute['attribute_code']); ?>"
                                           style="margin: 0 5px 0 0; position: inherit;">
                                    <i class="mw-sl__icon mw-sl__icon--website">
                                        <?php $icon = $block->getAttributeIcon($attribute['attribute_code']);
                                        if ($icon): ?>
                                            <img src="<?= $block->escapeUrl($icon); ?>"
                                                 alt="<?= $block->escapeHtml(__($attribute['frontend_label'])) ?>"/>
                                        <?php endif;?>
                                    </i>
                                    <span><?= $block->escapeHtml(__($attribute['frontend_label'])) ?><span>
                                </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </li>
            <li class="mw-sl__stores__details__website mw-sl__stores__filters__item" style="width: 100%;">
                <a class="mw-sl__clear_all__submit"> <?= $block->escapeHtml(__('Clear all')) ?></a>
                <button class="mw-sl__apply__submit"><?= $block->escapeHtml(
                        __('Apply')
                    ) ?></button>
            </li>
        </ul>
    </div>
    <div id="location_details"></div>
</div>

<script type="text/javascript" src="<?= $block->escapeUrl($block->getJsLink()) ?>"></script>
<script>
    var locations = [];
    var placesCoordinates = [];

    //Add markers on map
    <?php /** @var \MageWorx\Locations\Api\Data\LocationInterface $location */
    foreach ($locations as $location) :?>
    locations['<?= $block->escapeJs($location->getId())?>'] = <?= $block->escapeHtml($block->getLocationCoordinate($location))?>;
    <?php endforeach; ?>

    <?php /** @var \MageWorx\Locations\Api\Data\LocationInterface $location */
    $places = $block->getParentFilterList();

    foreach ($places as $place) :?>
    placesCoordinates['<?= $block->escapeJs($place->getId())?>'] = <?= $block->escapeHtml($block->getLocationCoordinate($place))?>;
    <?php endforeach; ?>
</script>
