<?php
use MageWorx\Locations\Api\Data\LocationInterface;

/** @var $block \MageWorx\StoreLocator\Block\LocationInfo\LocationDetail */
/** @var $location LocationInterface $location */
$location = $block->getLocation(); ?>
<div class="mw-sl__store__details__full" id="location-details_<?= $block->escapeHtml($location->getId()) ?>">
    <ul class="mw-sl__stores__details__icons">
        <li class="mw-sl__store__info__name"><?= /* @noEscape */
            $block->getLocationPageLink($location, __('Store Page')) ?></li>

        <?= /** @noEscape */ $block->getWorkingHoursHtml($location) ?>

        <?php if ($location->getPhoneNumber()) : ?>
            <li class="mw-sl__stores__details__tel"><i class="mw-sl__icon mw-sl__icon--tel">
                    <img src="<?= $block->escapeUrl(
                        $block->getViewFileUrl(
                            'MageWorx_StoreLocator::images/svg/phone.svg'
                        )
                              ); ?>"
                         alt="<?= $block->escapeHtml(__('Phone icon')) ?>"/>
                </i><a href="tel:<?= $block->escapeUrl($location->getPhoneNumber()); ?>">
                    <?= $block->escapeHtml($location->getPhoneNumber()); ?>
                </a>
            </li>
        <?php endif; ?>
        <?php if ($location->getEmail()) : ?>
            <li class="mw-sl__stores__details__email"><i class="mw-sl__icon mw-sl__icon--email">
                    <img src="<?= $block->escapeUrl(
                        $block->getViewFileUrl(
                            'MageWorx_StoreLocator::images/svg/mail.svg'
                        )
                              ); ?>"
                         alt="<?= $block->escapeHtml(__('Mail icon')) ?>"/>
                </i>
                <a href="mailto: <?= $block->escapeUrl($location->getEmail()); ?>"
                   target="_blank">
                    <?= $block->escapeHtml($location->getEmail()); ?>
                </a>
            </li>
        <?php endif; ?>
        <?php if ($location->getWebsiteUrl()) : ?>
            <li class="mw-sl__stores__details__website"><i class="mw-sl__icon mw-sl__icon--website">
                    <img src="<?= $block->escapeUrl(
                        $block->getViewFileUrl(
                            'MageWorx_StoreLocator::images/svg/www.svg'
                        )
                              ); ?>"
                         alt="<?= $block->escapeHtml(__('Website icon')) ?>"/>
                </i>
                <a href="https://<?= $block->escapeUrl($location->getWebsiteUrl()); ?>"
                   target="_blank">
                    <?= $block->escapeHtml($location->getWebsiteUrl()); ?>
                </a>
            </li>
        <?php endif; ?>
        <li class="mw-sl__stores__details__socials">
            <ul class="mw-sl__stores__details__socialslist">
                <?php if ($location->getInstagram()) : ?>
                    <li class="mw-sl__stores__details__socialslist__item">
                        <a href="https://instagram.com/<?= $block->escapeUrl($location->getInstagram()); ?>"
                           target="_blank">
                            <i class="mw-sl__icon mw-sl__icon--instagram">
                                <img src="<?= $block->escapeUrl(
                                    $block->getViewFileUrl(
                                        'MageWorx_StoreLocator::images/svg/instagram.svg'
                                    )
                                          ); ?>"
                                     alt="<?= $block->escapeHtml(__('Instagram icon')) ?>"/>
                            </i>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($location->getFacebook()) : ?>
                    <li class="mw-sl__stores__details__socialslist__item">
                        <a href="https://facebook.com/<?= $block->escapeUrl($location->getFacebook()); ?>"
                           target="_blank">
                            <i class="mw-sl__icon mw-sl__icon--facebook">
                                <img src="<?= $block->escapeUrl(
                                    $block->getViewFileUrl(
                                        'MageWorx_StoreLocator::images/svg/facebook.svg'
                                    )
                                          ); ?>"
                                     alt="<?= $block->escapeHtml(__('Facebook icon')) ?>"/>
                            </i>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($location->getWhatsapp()) : ?>
                    <li class="mw-sl__stores__details__socialslist__item">
                        <a href="https://wa.me/<?= $block->escapeUrl($location->getWhatsapp()); ?>" target="_blank">
                            <i class="mw-sl__icon mw-sl__icon--whatsapp">
                                <img src="<?= $block->escapeUrl(
                                    $block->getViewFileUrl(
                                        'MageWorx_StoreLocator::images/svg/whatsapp.svg'
                                    )
                                          ); ?>"
                                     alt="<?= $block->escapeHtml(__('Whatsapp icon')) ?>"/>
                            </i>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($location->getSkype()) : ?>
                    <li class="mw-sl__stores__details__socialslist__item">
                        <a href="skype:<?= $block->escapeUrl($location->getSkype()); ?>?call">
                            <i class="mw-sl__icon mw-sl__icon--skype">
                                <img src="<?= $block->escapeUrl(
                                    $block->getViewFileUrl(
                                        'MageWorx_StoreLocator::images/svg/skype.svg'
                                    )
                                          ); ?>"
                                     alt="<?= $block->escapeHtml(__('Skype icon')) ?>"/>
                            </i>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
        </li>
    </ul>
    <div class="mw-extra_attr">
        <div class="mw-extra_attr_columns">
            <ul class="mw-sl__stores__details__icons" style="min-width: 300px;">
                <?php foreach ($block->getExtraAttributes() as $attribute) : ?>
                    <?php if ($location->getData($attribute['attribute_code'])) : ?>
                        <li class="mw-sl__stores__details__website"  style="width: 50%;"><i class="mw-sl__icon mw-sl__icon--website">
                                <?php $icon = $block->getAttributeIcon($attribute['attribute_code']);
                                if ($icon): ?>
                                    <img src="<?= $block->escapeUrl($icon); ?>"
                                         alt="<?= $block->escapeHtml(__($attribute['frontend_label'])) ?>"/>
                                <?php endif;?>
                            </i>
                            <span><?= $block->escapeHtml(__($attribute['frontend_label'])) ?><span>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="mw-sl__stores__details__description"> <?= $block->getDescriptionHtml($location) ?></div>
</div>
