<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-2">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="customer-action">
                        <?php echo $this->getChildHtml("welcome-customer"); ?>

                        <div class="customer-links" data-move="customer-mobile">
                            <?php echo $this->getChildHtml("header.links"); ?>
                            
                        </div>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="language-currency">
                        <?php echo $this->getChildHtml("store_language"); ?>
                        <?php echo $this->getChildHtml("currency"); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-middle">
        <div class="container">
            <div class="middle-content">
                <div class="logo-container">
                    <?php echo $this->getChildHtml("logo"); ?>
                </div>

                <div class="right-container">
                    <div class="right-content">
                        <?php echo $this->getChildHtml("search-header"); ?>

                        <div class="minicart-header" data-move="minicart-mobile">
                            <?php echo $this->getChildHtml("minicart"); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="desktop-menu">
                <div class="vertical-block">
                    <?php
                    if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-vertical')->toHtml();
                    } else {
                        echo $this->getChildHtml("vertical-css");
                    }
                    ?>
                </div>

                <div class="horizontal-block">
                    <?php
                    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-promotion')->toHtml();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
