<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $viewModel \Improntus\PowerPay\ViewModel\Widgets */
/** @var $escaper \Magento\Framework\Escaper */

$viewModel = $block->getViewModel();
$storeId = $block->getStoreId();
if ($viewModel->getBannerWidgetEnabled($storeId)) :
    ?>
    <mo-banner mo-client-id="<?= $escaper->escapeHtml($viewModel->getClientId($storeId)); ?>"></mo-banner> <br />
<?php endif; ?>
