<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $viewModel \Improntus\PowerPay\ViewModel\Widgets */
/** @var $escaper \Magento\Framework\Escaper */

$viewModel = $block->getViewModel();
$storeId = $block->getStoreId();
if ($viewModel->getHeaderWidgetEnabled($storeId)) :
?>
<mo-header mo-client-id="<?= $escaper->escapeHtml($viewModel->getClientId($storeId)); ?>"></mo-header> <br />
<?php endif; ?>
