<?php
/** @var $block \MageWorx\StoreLocator\Block\Filter */
?>
<div class="mw-sl__stores mw-filter_for_list">
    <div class="mw-sl__stores__header">
        <div class="mw-sl__stores__header__item mw-sl__stores__header__item_pin">
            <i class="mw-sl__icon--pin">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('MageWorx_StoreLocator::images/svg/pin.svg'));?>"
                     alt="<?= $block->escapeHtml(__('Pin icon'))?>"/>
            </i></div>
        <div class="mw-sl__stores__header__item">
            <p id="sl__stores__current_place" class="mw-sl__stores__current"><?= $block->escapeHtml($block->getCurrentPlaceName()); ?></p>
            <p class="mw-sl__stores__current mw-store-locator-inactive-place mw-sl__stores__current_all_stores">
                <?= $block->escapeHtml(__('All Stores')); ?>
            </p>
            <?php foreach ($block->getParentFilterList() as $code => $name) :?>
                <p class="mw-sl__stores__current mw-store-locator-inactive-place mw-sl__stores__current_<?= $code; ?>">
                    <?= $name; ?>
                </p>
            <?php endforeach; ?></div>
    </div>
    <div class="mw-sl__stores__filters">
        <ul>
            <li class="mw-sl__stores__filters__item mw-sl__stores__filters__item-map" id="all_stores">
                <?= $block->escapeHtml(__('All Stores')); ?>
            </li>
            <?php foreach ($block->getParentFilterList() as $code => $name) : ?>
                <li class="mw-sl__stores__filters__item mw-sl__stores__filters__item-map" id="<?= $block->prepareCode($code)?>">
                    <?= $name; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<script type="text/javascript" src="<?= $block->getJsLink() ?>"></script>
<script>
    var locations = [];
    //Add markers on map
    <?php /** @var \MageWorx\Locations\Api\Data\LocationInterface $location */
    $locations = $block->getLocations();

    foreach ($locations as $location) :?>
    locations['<?= $location->getId()?>'] = <?= $block->escapeHtml($block->getLocationCoordinate($location))?>;
    <?php endforeach; ?>
</script>