<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


$orderItems = $block->getOrderAllVisibleItems();
$orderData= $block->getOrderData();
$billing =  $orderData->getBillingAddress()->getData();
$shipping = $orderData->getShippingAddress()->getData();
// $currencyCode=$block->getCurrency();
$currencyCode="S/"; 
$currencyDesc=$block->getCurrencyCode();




$payment = $orderData->getPayment();


if($payment->getMethod()=="pagoefectivo_pay"){ 
    $cipUrl = $payment->getAdditionalInformation('cip_url');
    echo '<iframe id="vexpeIframe" src="'.$cipUrl.'" width="100%" style="min-height:2160px;" target="_self" scrolling="no" frameborder="0"> 
        <p>Su navegador no soporta iframes.</p> 
    </iframe>';

}
?>



<div class="orden_success_page">

    <div class="title">
        Gracias por su pedido
    </div>
    <div class="content" id="areaImprimir">

        <?php
            if (!empty($_SESSION['autorizado'])){

                if ($_SESSION['autorizado']=='1'){

             

                $media_dir = $block->getMediaDirectory();
                
                $imagen= $block->getHelperConfig('payment/visanet_pay/upload_image');
                $logostore = $media_dir."image/".$imagen;
                $namestore =  $block->getHelperConfig('general/store_information/name');
                $telefonostore = $block->getHelperConfig('general/store_information/phone');
                $citystore = $block->getHelperConfig('general/store_information/city');
                $direccion1store = $block->getHelperConfig('general/store_information/street_line1');
                $direccionstore = $citystore." - ".$direccion1store;
                $politicas_devolucion = $block->getHelperConfig('general/store_information/politicas_devolucion');
                $terminos_condiciones = $block->getHelperConfig('general/store_information/terminos_condiciones');
                $date  = $_SESSION['fecha_pedido'];
                    $year = substr($date, 0, 2);
                    $month = substr($date, 2, 2);
                    $day = substr($date, 4, 2);
                    $hora = substr($date, 6, 2);
                    $min = substr($date, 8, 2);
                    $seg = substr($date, 10, 2);
                
                    $usoLosPuntos=false;
                    if(isset($_SESSION['USOLOSPUNTOS'])==true){
                        $usoLosPuntos=($_SESSION['USOLOSPUNTOS']);
                    }
                    $esUnaCombinacionDepago=false;
                    if(isset($_SESSION['ESUNACOMBINACIONDEPAGO'])==true){
                        $esUnaCombinacionDepago=($_SESSION['ESUNACOMBINACIONDEPAGO']);
                    }

                    if($usoLosPuntos==false){
        ?>

                        <div>
                            <p> <div align="center"><img src="<?=$logostore;?>" alt=""> </div></p>

                            <p><span><strong>Teléfono: </strong> </span> <?=$telefonostore;?> </p>
                            <p><span><strong>Dirección Comercial: </strong> </span> <?=$direccionstore;?> </p>

                            <p><span><strong>Número de Tarjeta: </strong> </span> <?=$_SESSION['tarjeta']?></p>
                            <p><span><strong>Fecha y hora del pedido: </strong> </span> <?="20".$year."-".$month."-". $day ." ".$hora .":".  $min.":".$seg;?> </p>
                            <p><span><strong>Importe: </strong> </span> <?=$currencyCode.number_format($block->getOrderGrandTotal(), 2, '.', ',')?></p>
                            <p><span><strong>Moneda: </strong> </span><?=$currencyDesc?>  </p>
                            <p><span><strong>Nombre de tarjetahabiente: </strong> </span> <?=$shipping['firstname'].' '.$shipping['lastname']?> </p>

                            <p><span><strong>Descripción del código de acción: </strong> </span>  <?=$_SESSION['DSC_COD_ACCION']?></p>
                            <p><span><strong>Políticas de devolución: </strong> </span>  <a href="<?=$politicas_devolucion;?>" target="_blank">Ver Aquí</a> </p>
                            <p><span><strong>Términos y Condiciones : </strong> </span> <a href="<?=$terminos_condiciones;?>" target="_blank">Ver Aquí</a>  </p>
                            <p><strong>Estima cliente debe imprimir y guardar este recibo de transacción</strong></p>
                        </div>

                        <div class="subtitle">
                            Hemos recibido su orden y será procesada, le enviamos un email de confirmación con los detalles y información del envío. El detalle de su pedido:
                        </div>
 
        <?php
                }
                if($usoLosPuntos==true && $esUnaCombinacionDepago==true)
                {
                    ?>
                          <div>
                            <p> <div align="center"><img src="<?=$logostore;?>" alt=""> </div></p>

                            <p><span><strong>Teléfono: </strong> </span> <?=$telefonostore;?> </p>
                            <p><span><strong>Dirección Comercial: </strong> </span> <?=$direccionstore;?> </p>

                            <p><span><strong>Número de Tarjeta: </strong> </span> <?=$_SESSION['tarjeta']?></p>
                            <p><span><strong>Fecha y hora del pedido: </strong> </span> <?="20".$year."-".$month."-". $day ." ".$hora .":".  $min.":".$seg;?> </p>
                            <p><span><strong>Importe: </strong> </span> <?=$currencyCode.number_format($block->getOrderGrandTotal(), 2, '.', ',')?></p>
                            <p><span><strong>Moneda: </strong> </span><?=$currencyDesc?>  </p>
                            <p><span><strong>Nombre de tarjetahabiente: </strong> </span> <?=$shipping['firstname'].' '.$shipping['lastname']?> </p>

                            <p><span><strong>Descripción del código de acción: </strong> </span>  <?=$_SESSION['DSC_COD_ACCION']?></p>
                            <p><span><strong>Programa:  </strong> </span> <?=$_SESSION['EXCHANGE_PROGRAM_NAME']?></p>
                            <p><span><strong>Monto con tarjeta:  </strong> </strong> </span><?=$currencyDesc?> </span>  <?=$_SESSION['MONTOTARJETACOMBINADA']?></p>
                            <p><span><strong>Puntos canjeados:   </strong> </span> <?=$_SESSION['REDEEMED_POINTS']?> <span>(<strong>equivale a  </strong> </span></strong> </span><?=$currencyDesc?> <?=$_SESSION['REDEEMED_EQUIVALENT_AMOUNT']?>)</p>
                            <p><span><strong>ID canje:   </strong> </span> <?=$_SESSION['EXCHANGE_ID']?> 
                            <p><span><strong>Políticas de devolución: </strong> </span>  <a href="<?=$politicas_devolucion;?>" target="_blank">Ver Aquí</a> </p>
                            <p><span><strong>Términos y Condiciones : </strong> </span> <a href="<?=$terminos_condiciones;?>" target="_blank">Ver Aquí</a>  </p>
                            <p><strong>Estima cliente debe imprimir y guardar este recibo de transacción</strong></p>
                        </div>

                        <div class="subtitle">
                            Hemos recibido su orden y será procesada, le enviamos un email de confirmación con los detalles y información del envío. El detalle de su pedido:
                        </div>
                    <?php
                }

                if($usoLosPuntos==true && $esUnaCombinacionDepago==false)
                {
                    ?>
                          <div>
                            <p> <div align="center"><img src="<?=$logostore;?>" alt=""> </div></p>

                            <p><span><strong>Teléfono: </strong> </span> <?=$telefonostore;?> </p>
                            <p><span><strong>Dirección Comercial: </strong> </span> <?=$direccionstore;?> </p>

                            <p><span><strong>Fecha y hora del pedido: </strong> </span> <?="20".$year."-".$month."-". $day ." ".$hora .":".  $min.":".$seg;?> </p>
                            <p><span><strong>Importe: </strong> </span> <?=$currencyCode.number_format($block->getOrderGrandTotal(), 2, '.', ',')?></p>
                            <p><span><strong>Moneda: </strong> </span><?=$currencyDesc?>  </p>
                            <p><span><strong>Nombre de tarjetahabiente: </strong> </span> <?=$shipping['firstname'].' '.$shipping['lastname']?> </p>

                            <p><span><strong>Descripción del código de acción: </strong> </span>  <?=$_SESSION['DSC_COD_ACCION']?></p>
                            <p><span><strong>Programa:  </strong> </span> </strong> </span><?=$currencyDesc?> <?=$_SESSION['EXCHANGE_PROGRAM_NAME']?></p>
                            <p><span><strong>Puntos canjeados:   </strong> </span> <?=$_SESSION['REDEEMED_POINTS']?> <span>(<strong>equivale a   </strong> </span></strong> </span><?=$currencyDesc?> <?=$_SESSION['REDEEMED_EQUIVALENT_AMOUNT']?>)</p>
                            <p><span><strong>ID canje:   </strong> </span> <?=$_SESSION['EXCHANGE_ID']?> 
                            <p><span><strong>Políticas de devolución: </strong> </span>  <a href="<?=$politicas_devolucion;?>" target="_blank">Ver Aquí</a> </p>
                            <p><span><strong>Términos y Condiciones : </strong> </span> <a href="<?=$terminos_condiciones;?>" target="_blank">Ver Aquí</a>  </p>
                            <p><strong>Estima cliente debe imprimir y guardar este recibo de transacción</strong></p>
                        </div>

                        <div class="subtitle">
                            Hemos recibido su orden y será procesada, le enviamos un email de confirmación con los detalles y información del envío. El detalle de su pedido:
                        </div>


                    <?php
                    
                }

            }
            else
            {

        ?>
                 <p><strong>Desgraciadamente tu pedido no puede procesarse el banco/comercio ha rechazado tu transación. Por favor intenta realizar la compra de nuevo</strong></p> <br>
                 <p><span><strong>Fecha y Hora: </strong></span> <?=$_SESSION['fecha_pedido']?></p>
                 <p><span><strong>Motivo:</strong></span> <?"Operación denegada. Transacción no puede ser procesada"?> </p>
                 <p><span><strong>Moneda:</strong></span><?=$currencyDesc?></p>
     <?php
            }

        }

    ?>
     
        <div class="pedido-numero">
            <a href="<?PHP echo $block->getViewOrderUrl();?>"> Número de pedido: <span style="margin-left: 5px;"> #<?PHP echo $block->escapeHtml($block->getOrderId()); ?> </span> </a>
        </div>

        <div class="pedido-items">
            <table>
                <tr class="pedido_header">
                    <td width="80" align="center">
                        #
                    </td>
                    <td width="250">
                        Item
                    </td>
                    <td width="100" align="center">
                        Cantidad
                    </td>
                    <td width="100" align="center">
                        SubTotal
                    </td>
                </tr>

                <?php
                
                $n = 1;
                $total = 0;

                foreach ($orderItems as $item) {

               
                    $_product = $block->getProduct($item->getProductId());
                    $imageHelper  = $this->helper(\Magento\Catalog\Helper\Image::class);


                    if($item->getProduct()->getTypeId() == 'configurable'){
                        $realProductChild = $block->getRealProduct($item->getSku());
                        $image_url = $imageHelper->init($realProductChild, 'product_page_image_small')->setImageFile($_product->getFile())->resize(100, 100)->getUrl();

                        if (empty($image_url)){
                            $image_url = $imageHelper->getDefaultPlaceholderUrl('image');
                        }
                    }
                    else{
                        $image_url = $imageHelper->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize(100, 100)->getUrl();

                        if (empty($image_url)){
                            $image_url = $imageHelper->getDefaultPlaceholderUrl('image');
                        }
                    }

                    $itemData = $item->getData();
                    $total+=$itemData['row_total'];
                    // print_r($item->getData());
                    ?>

                    <tr clas="pedido_registro">
                        <td width="80" align="center">
                            <img src="<?=$image_url?>" width="75" height="75" alt="">
                        </td>
                        <td width="250">
                            <div>
                                <?php echo $item->getName(); ?>
                            </div>
                            <div>
                                SKU: <?php echo $item->getSKU(); ?>
                            </div>
                        </td>
                        <td width="100" align="center">
                            <?PHP echo (int)$item->getQtyOrdered(); ?>
                        </td>
                        <td width="100" align="center">
                            <?PHP  echo number_format($itemData['row_total'],2); ?>
                        </td>
                    </tr>

                    <?PHP

                    $n++;
                }

                ?>
 

                <tr class="pedido_header">
                    <td colspan="2"></td>
                    <td align="right"> Sub Total: </td>
                    <td align="center"> <?PHP echo $currencyCode.number_format($orderData['base_subtotal'],2);  ?></td>
                </tr>

                <tr class="pedido_header">
                    <td colspan="2"></td>
                    <td align="right"> Costo de envío: </td>
                    <td align="center"> <?PHP echo $currencyCode.number_format($orderData['shipping_amount'],2);  ?></td>
                </tr>

                <?PHP 

                    if( ($orderData['discount_amount']*1) > 0){

                ?>

                <tr class="pedido_header">
                    <td colspan="2"></td>
                    <td align="right"> - Total descuentos: </td>
                    <td align="center"> <?PHP echo $currencyCode.number_format($orderData['discount_amount'],2);  ?></td>
                </tr>

                <?PHP 

                    }
                ?>

                <tr class="pedido_header">
                    <td colspan="2"></td>
                    <td align="right"> Total: </td>
                    <td align="center"> <?PHP echo $currencyCode.number_format($orderData['grand_total'],2);  ?></td>
                </tr>


            </table>

        </div>

        <div class="direcciones">

            <div class="envio">
                <div class="subtitle">
                    Dirección de envío
                </div>

                <div class="direccion_content">
                    <div>
                        <?PHP
                        echo $shipping['firstname'].' '.$shipping['lastname'];
                        ?>
                    </div>
                    <div>
                        <?php

                        if(is_array($shipping['street'])) {
                            echo implode(",", $shipping['street']);
                        } else {
                            echo $shipping['street'];
                        }

                        //echo implode(',', $shipping['street']);

                        ?>
                    </div>
                    <div>
                        <?PHP
                        echo $shipping['city'];
                        ?>
                    </div>
                </div>

            </div>

            <div class="facturacion">

                <div class="subtitle">
                    Dirección de facturación
                </div>

                <div class="direccion_content">
                    <div>
                        <?PHP
                        echo $billing['firstname'].' '.$billing['lastname'];
                        ?>
                    </div>
                    <div>
                        <?PHP
                        if(is_array($billing['street'])) {
                            echo implode(",", $billing['street']);
                        } else {
                            echo $billing['street'];
                        }
                        //echo implode(',', $billing['street']);
                        ?>
                    </div>
                    <div>
                        <?php
                        if(is_array($billing['city'])) {
                            echo implode(",", $billing['city']);
                        } else {
                            echo $billing['city'];
                        }
                        //echo $billing['city'];
                        ?>
                    </div>
                </div>

            </div>

        </div> 
        <div class="">
                <input class="btn btn-default" type="button" onclick="printDiv('areaImprimir')" value="Imprimir" />

        </div>
    </div>

</div>
<style>
    /* Success page */

    .orden_success_page{
        max-width: 900px;
        background-color: #FFF;
        margin-top: 30px;
    }

    .orden_success_page .title{
        color:#000;
        font-size: 24px;
        font-weight: bold;
        padding:15px 0px;
    }

    .orden_success_page .subtitle{
        margin-top: 10px;
    }

    .orden_success_page .content .pedido-numero{
        font-size: 20px;
        margin-top: 10px;
    }

    .orden_success_page .pedido_header{
        background-color: #F2F2F2;
        margin-top:15px;
    }

    .orden_success_page .pedido-items{
        color:#333;
    }

    .orden_success_page .direcciones{
        display: table;
        width: 100%;
        margin-bottom: 20px;
    }

    .orden_success_page .direcciones .subtitle{
        margin-top: 10px;
        margin-bottom: 5px;
        font-size: 20px;
        color:#333;

    }

    .orden_success_page .direcciones .envio{
        width: 50%;
        float: left;
    }

    .orden_success_page .direcciones .facturacion{
        width: 50%;
        float: left;
    }
</style>
<script>
    function printDiv(nombreDiv) {
        var contenido= document.getElementById(nombreDiv).innerHTML;
        var contenidoOriginal= document.body.innerHTML;
        document.body.innerHTML = contenido;
        window.print();
        document.body.innerHTML = contenidoOriginal;
    }
</script>